### ISSUE TITLE
Block navigation from the editor when there are unsaved changes

### ISSUE THREAD

**Issue by davidqnz** [david-qz/glsl-playground#21]
I'm not sure how to do this with react-router. If all else fails I guess the editor could be split off into a separate document and we could use `window.onbeforeunload` to pop up the native confirmation box.

**Comment by forestheims** [comment]
for the conditional prevention of navigation react-router 5 has ```<Prompt />```
- https://v5.reactrouter.com/core/api/Prompt

though I've heard this is deprecated for react router 6

https://github.com/remix-run/react-router/issues/8139#issuecomment-954425560

^ this goes into depth on it more. You might find some other helpful links in this conversation

**Comment by david-qz** [comment]
That issue thread was really useful! I had to downgrade `react-router-dom` to `v6.3.x` from `v6.4.x` to use the implementations shared in that thread, but they seem to work well. I will have to make some UX decisions now.

**Comment by david-qz** [comment]
Closed via c08d639e51e1556bf20d927351afe2cf39d464f1
